CREATE TABLE BRANCH (BRANCH_NAME VARCHAR(30), 
ASSETS VARCHAR(30), 
CITY VARCHAR(20), 
PRIMARY KEY(BRANCH_NAME));

CREATE TABLE EMPLOYEE ( 
E_SSN VARCHAR(12), 
E_TELNO INT, 
E_NAME VARCHAR(20), 
E_STDATE VARCHAR(20), 
E_LENGTH INT, 
MGR_SSN VARCHAR(12), 
BRANCH_NAME VARCHAR(30),
E_TYPE VARCHAR(30),
PRIMARY KEY(E_SSN), 
FOREIGN KEY(BRANCH_NAME) REFERENCES BRANCH(BRANCH_NAME));

CREATE TABLE DEPENDENT ( 
D_NAME VARCHAR(20), 
E_SSN VARCHAR(12), 
PRIMARY KEY(D_NAME), 
FOREIGN KEY (E_SSN) REFERENCES EMPLOYEE(E_SSN));

CREATE TABLE ACCOUNT(
ACC_NO INT, 
ACC_BAL FLOAT, 
TRANS_DATE VARCHAR(10), 
ACCOUNT_TYPE VARCHAR(20), 
BRANCH_NAME VARCHAR(30), 
PRIMARY KEY(ACC_NO), 
FOREIGN KEY (BRANCH_NAME) REFERENCES BRANCH(BRANCH_NAME));

CREATE TABLE LOAN(
LOAN_NO INT, 
LOAN_AMT FLOAT, 
BRANCH_NAME VARCHAR(20), 
PRIMARY KEY (LOAN_NO), 
FOREIGN KEY (BRANCH_NAME) REFERENCES BRANCH(BRANCH_NAME));

CREATE TABLE CUSTOMER ( 
C_SSN VARCHAR(12), 
C_NAME VARCHAR(20), 
C_STREET VARCHAR(20), 
C_CITY VARCHAR(20), 
E_SSN VARCHAR(12),
PRIMARY KEY (C_SSN),
FOREIGN KEY (E_SSN) REFERENCES EMPLOYEE(E_SSN));

CREATE TABLE LOAN_PAYMENT( 
PAYMENT_NO INT, 
AMOUNT FLOAT, 
PAYMENT_DATE VARCHAR(10), 
LOAN_NO INT, 
LOAN_PAY_NO VARCHAR(6), 
PRIMARY KEY(PAYMENT_NO), 
FOREIGN KEY (LOAN_NO) REFERENCES LOAN(LOAN_NO));

CREATE TABLE SAVINGS( 
SV_DEPO FLOAT, 
SV_WITH FLOAT, 
INT_RATE FLOAT, 
ACC_NO INT, 
FOREIGN KEY (ACC_NO) REFERENCES ACCOUNT(ACC_NO));

CREATE TABLE CHECKINGS( 
CK_DEPO FLOAT, 
CK_WITH FLOAT, 
OVERDRAFTS FLOAT, 
ACC_NO INT, 
FOREIGN KEY (ACC_NO) REFERENCES ACCOUNT(ACC_NO));

CREATE TABLE CUST_LOAN( 
C_SSN VARCHAR(12), 
LOAN_NO INT,
FOREIGN KEY (C_SSN) REFERENCES CUSTOMER(C_SSN),
FOREIGN KEY (LOAN_NO) REFERENCES LOAN(LOAN_NO));

CREATE TABLE CUST_ACCOUNT( 
C_SSN VARCHAR(12), 
ACC_NO INT,
FOREIGN KEY (C_SSN) REFERENCES CUSTOMER(C_SSN),
FOREIGN KEY (ACC_NO) REFERENCES ACCOUNT(ACC_NO));